name: UnendurableLove # the plugins name as it should appear in the plugin list /pl
version: '${version}' # the plugin's version
author: Alloca
main: me.Alloca.UnendurableLove.UnendurableLove
api-version: 1.18 # the version of the API you want to use, required starting with 1.13
softdepend: [BKCommonLib]
commands:
  unleash:
    description: Unleash a pet
    usage: /<command> [pet]
    permission: UnendurableLove.UnleashPermission
  chooseTag:
    description: Choose a tag you can label pets
    usage: /<command> [tag]
    permission: UnendurableLove.ChooseTagPermission
  letSpeak:
    description: Let a pet speak
    usage: /<command> [pet]
    permission: UnendurableLove.LetSpeakPermission